export const LOAD_BREEDS_API_REQUEST = "LOAD_BREEDS_API_REQUEST";
export const LOAD_BREEDS_API_SUCCESS = "LOAD_BREEDS_API_SUCCESS";
export const LOAD_BREEDS_API_FAILURE = "LOAD_BREEDS_API_FAILURE";

export const SELECT_BREED = "SELECT_BREED";
export const LOAD_SELECTED_BREED_DOGS_SUCCESS = "LOAD_SELECTED_BREED_DOGS_SUCCESS";
export const LOAD_SELECTED_BREED_DOGS_FAILURE = "LOAD_SELECTED_BREED_DOGS_FAILURE";

export const LOAD_BREED_IMAGES_API_REQUEST = "LOAD_BREED_IMAGES_API_REQUEST";
export const LOAD_BREED_IMAGES_API_SUCCESS = "LOAD_BREED_IMAGES_API_SUCCESS";
export const LOAD_BREED_IMAGES_API_FAILURE = "LOAD_BREED_IMAGES_API_FAILURE";

